"use client";

import { Layers } from "lucide-react";

export function Canvas() {
  return (
    <div className="flex h-full flex-col bg-muted/30">
      {/* Header */}
      <div className="flex items-center gap-2 border-b border-border px-4 py-3">
        <Layers className="h-4 w-4 text-muted-foreground" />
        <span className="text-sm font-medium text-muted-foreground">Canvas</span>
      </div>

      {/* Content area - placeholder for future pinned widgets */}
      <div className="flex flex-1 flex-col p-8 gap-6 overflow-auto">
        
        {/* Pinned Widgets Placeholder */}
        <div className="rounded-xl border border-dashed border-border p-8">
            <div className="flex flex-col items-center justify-center text-center">
                 <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-muted/50">
                    <Layers className="h-6 w-6 text-muted-foreground" />
                 </div>
                 <h3 className="text-base font-medium text-foreground">Pinned Widgets</h3>
                 <p className="text-sm text-muted-foreground max-w-sm mt-1">
                    Important widgets pinned for quick access will appear here in Phase 8.
                 </p>
            </div>
        </div>

        {/* Interactable Widgets Placeholder */}
        <div className="rounded-xl border border-dashed border-border p-8 flex-1 min-h-[200px]">
             <div className="flex flex-col items-center justify-center text-center h-full">
                 <h3 className="text-base font-medium text-foreground">Interactable Widgets</h3>
                 <p className="text-sm text-muted-foreground max-w-sm mt-1">
                    Dynamic, interactive components generated by the agent during conversation (Phase 5).
                 </p>
            </div>
        </div>

      </div>

      {/* Quick Actions Bar */}
      <div className="border-t border-border p-3 bg-muted/10">
        <div className="flex items-center gap-2">
            <button className="px-3 py-1.5 text-xs font-medium bg-secondary text-secondary-foreground rounded-md opacity-50 cursor-not-allowed" disabled>
                Pin Widget
            </button>
             <button className="px-3 py-1.5 text-xs font-medium bg-secondary text-secondary-foreground rounded-md opacity-50 cursor-not-allowed" disabled>
                Save Template
            </button>
             <button className="px-3 py-1.5 text-xs font-medium bg-secondary text-secondary-foreground rounded-md opacity-50 cursor-not-allowed" disabled>
                Remix
            </button>
        </div>
      </div>
    </div>
  );
}
