"use client";

import { TamboThreadInputProvider, TamboThreadProvider } from "@tambo-ai/react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs";
import { ChatThread } from "../chat/ChatThread";
import { ChatComposer } from "../chat/ChatComposer";
import { EventTimeline } from "../events/EventTimeline";
import { MessageSquare, FileBox, Server, Database, Clock } from "lucide-react";
import { useStore, DOCK_TABS, type DockTab } from "@/lib/store";

export function Dock() {
  const { state, setActiveDockTab, hasTambo } = useStore();
  const activeDockTab: DockTab = state.ui.activeDockTab;

  const dockTabs: readonly string[] = DOCK_TABS;
  const isDockTab = (tab: string): tab is DockTab => dockTabs.includes(tab);

  return (
    <div className="flex h-full flex-col bg-background">
      <Tabs
        id="dock-tabs"
        value={activeDockTab}
        onValueChange={(tab) => {
          if (!isDockTab(tab)) return;
          setActiveDockTab(tab);
        }}
        className="flex h-full flex-col"
      >
        {/* Tab List */}
        <div className="shrink-0 border-b border-border px-2">
          <TabsList variant="line" className="h-10">
            <TabsTrigger value="chat" className="gap-1.5" disabled={!hasTambo}>
              <MessageSquare className="h-3.5 w-3.5" />
              <span className="text-xs">Chat</span>
            </TabsTrigger>
            <TabsTrigger value="events" className="gap-1.5">
              <Clock className="h-3.5 w-3.5" />
              <span className="text-xs">Events</span>
            </TabsTrigger>
            <TabsTrigger value="artifacts" className="gap-1.5">
              <FileBox className="h-3.5 w-3.5" />
              <span className="text-xs">Artifacts</span>
            </TabsTrigger>
            <TabsTrigger value="mcp" className="gap-1.5">
              <Server className="h-3.5 w-3.5" />
              <span className="text-xs">MCP</span>
            </TabsTrigger>
            <TabsTrigger value="db" className="gap-1.5">
              <Database className="h-3.5 w-3.5" />
              <span className="text-xs">DB</span>
            </TabsTrigger>
          </TabsList>
        </div>

        {/* Chat Tab */}
        <TabsContent value="chat" className="flex flex-1 flex-col m-0 overflow-hidden">
          {hasTambo ? (
            <TamboThreadProvider>
              <TamboThreadInputProvider>
                <div className="flex-1 overflow-auto">
                  <ChatThread />
                </div>
                <div className="shrink-0 border-t border-border p-3">
                  <ChatComposer />
                </div>
              </TamboThreadInputProvider>
            </TamboThreadProvider>
          ) : (
            <div className="flex h-full items-center justify-center px-6 text-center text-sm text-muted-foreground">
              Chat is disabled (missing <code className="font-mono">NEXT_PUBLIC_TAMBO_API_KEY</code>).
            </div>
          )}
        </TabsContent>

        {/* Events Tab */}
        <TabsContent value="events" className="flex-1 m-0 overflow-auto">
          <EventTimeline />
        </TabsContent>


        {/* Placeholder tabs */}
        <TabsContent value="artifacts" className="flex-1 m-0 overflow-auto">
          <div className="flex h-full flex-col items-center justify-center p-6 text-center text-muted-foreground">
            <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-muted">
              <FileBox className="h-8 w-8 text-muted-foreground" />
            </div>
            <h3 className="mb-2 text-lg font-medium text-foreground">No artifacts yet</h3>
            <p className="text-sm">
              Artifacts generated by the agent will appear here.
            </p>
          </div>
        </TabsContent>
        <TabsContent value="mcp" className="flex-1 m-0">
          <div className="flex h-full flex-col items-center justify-center p-6 text-center text-muted-foreground">
             <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-muted">
              <Server className="h-8 w-8 text-muted-foreground" />
            </div>
            <h3 className="mb-2 text-lg font-medium text-foreground">MCP Servers</h3>
            <p className="mb-4 text-sm max-w-xs">
              Connect external tools and data sources via the Model Context Protocol.
            </p>
            <button className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground opacity-50 cursor-not-allowed" disabled>
              Connect MCP Server
            </button>
            <p className="mt-4 text-xs text-muted-foreground">(Coming in Phase 6)</p>
          </div>
        </TabsContent>
        <TabsContent value="db" className="flex-1 m-0">
          <div className="flex h-full flex-col items-center justify-center p-6 text-center text-muted-foreground">
             <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-muted">
              <Database className="h-8 w-8 text-muted-foreground" />
            </div>
            <h3 className="mb-2 text-lg font-medium text-foreground">Database</h3>
            <p className="mb-4 text-sm max-w-xs">
              Manage your local SQLite database and view table schemas.
            </p>
             <button className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground opacity-50 cursor-not-allowed" disabled>
              Upload SQLite / Connect DB
            </button>
            <p className="mt-4 text-xs text-muted-foreground">(Coming in Phase 5)</p>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
